import { Router } from "express";
import adminAuthRouter from "./adminAuthRouteHandler.js";
import { verifyToken } from "../../Middlewares/AuthMiddleware.js";
import {
  addPizza,
  addProduct,
  allOrders,
  dashboard,
  deletePizza,
  deleteProduct,
  deleteUser,
  getAllUsers,
  getOrderAccStatus,
  getPizzaDetails,
  getPizzas,
  getUserCart,
  getUserWithNameOrEmail,
  imageUpload,
  inventory,
  OrderDetails,
  updateOrderStatus,
  updatePizza,
  updateProduct,
  updateUser,
  userOrders,
  orderData,
  revenueData,
} from "../../Controllers/Admin/AdminMiscController.js";
import { upload } from "../../utils/util-functions.js";

const AdminRouter = Router();

// Middleware for All the auth Routes related to Admin.
AdminRouter.use("/auth", adminAuthRouter);

AdminRouter.get("/dashboard", verifyToken, dashboard);
AdminRouter.get("/dashboard/revenue", verifyToken, revenueData); // -Data for LineChart creation which denotes the revenue generated by the store in each month
AdminRouter.get("/dashboard/order", verifyToken, orderData); // -Data for PieChart creation which denotes the ration of status of orders

// Admin - Inventory Routes
AdminRouter.get("/inventory", verifyToken, inventory);
AdminRouter.post("/addproduct", verifyToken, addProduct);
AdminRouter.patch("/updateproduct", verifyToken, updateProduct);
AdminRouter.delete("/deleteproduct", verifyToken, deleteProduct);

// Admin - pizza Routes
/**
 *  Used to upload the image of pizza Locally using multer.And Not being used in the deployed version AS Cloudinary is being used.
 */
AdminRouter.post(
  "/pizza/upload",
  verifyToken,
  upload.single("image"),
  imageUpload
);

AdminRouter.get("/get-pizzas", verifyToken, getPizzas);
AdminRouter.get("/pizza/get-pizza-details", verifyToken, getPizzaDetails);
AdminRouter.post("/addpizza", verifyToken, addPizza);
AdminRouter.patch("/updatepizza", verifyToken, updatePizza);
AdminRouter.delete("/deletepizza", verifyToken, deletePizza);

// Admin - User Routes
AdminRouter.get("/users-list", verifyToken, getAllUsers);
AdminRouter.get("/user/search", verifyToken, getUserWithNameOrEmail);
AdminRouter.patch("/update-user", verifyToken, updateUser);
AdminRouter.delete("/delete-user", verifyToken, deleteUser);

AdminRouter.get("/user/cart",verifyToken,getUserCart)

// Admin -> User - Order Details
AdminRouter.get("/orders", verifyToken, allOrders);
AdminRouter.patch("/order", verifyToken, updateOrderStatus);
AdminRouter.get("/user/orders", verifyToken, userOrders);
AdminRouter.get("/orders/filtered", verifyToken, getOrderAccStatus); // -> GET -> status : query -> orders according to given valid status like "completed" or "pending"
AdminRouter.get("/order/detail", verifyToken, OrderDetails);

export default AdminRouter;
