import React, { useEffect } from 'react'

const DashBoardCharts = () => {
    useEffect(()=>{
        const fetchRevenueData = async() =>{

        };
        const fetchOrderData = async() =>{

        };
        fetchRevenueData(); //-> fetch data of revenue generated by the store in each month
        fetchOrderData(); // -> fetch data of orders from each month (like count of orders,cancelled,placed,delivered)
    },[]);
  return (
    <div>
      
    </div>
  )
}

export default DashBoardCharts
